# Description Data

# Data Collection

Langkah pertama dalam Data Understanding adalah pengumpulan data (data collection). Pada tahap ini, data dikumpulkan dari berbagai sumber yang relevan, seperti database, file CSV atau Excel, API, maupun sistem internal organisasi. Maksud dari langkah ini adalah memastikan bahwa data yang digunakan sesuai dengan tujuan penelitian, lengkap, dan representatif terhadap permasalahan yang akan dianalisis. Tanpa proses pengumpulan yang tepat, hasil analisis berisiko tidak relevan dengan kebutuhan penelitian.

# Tujuan Data Collection

Berikut adalah tujuan Data Collection:
1. Memperoleh data yang relevan dengan permasalahan atau tujuan penelitian.
2. Mengumpulkan data dari sumber yang terpercaya, seperti database, file CSV/Excel, API, atau sistem internal.
3. Memastikan kelengkapan data, baik dari segi jumlah sampel maupun variabel yang dibutuhkan.
4. Menjamin data bersifat representatif, sehingga dapat menggambarkan kondisi sebenarnya.
5. Mendukung proses analisis selanjutnya, agar tahap deskripsi, eksplorasi, dan pemodelan dapat dilakukan dengan tepat.
6. Mengurangi risiko kesalahan analisis, karena data yang digunakan sudah sesuai dengan kebutuhan dan tujuan penelitian.

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('D:/Pendata/materi/IRIS.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Informasi Dataset

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

## Statistik Deskriptif

In [9]:
df.describe(include='all')

        sepal_length  sepal_width  petal_length  petal_width      species
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [15]:
import pandas as pd

df = pd.read_csv("IRIS.csv")
kolom = df['sepal_width']

print("Jumlah data        :", kolom.count())
print("Rata-rata          :", round(kolom.mean(), 2))
print("Nilai minimal      :", kolom.min())
print("Q1                 :", kolom.quantile(0.25))
print("Q2 (Median)        :", kolom.quantile(0.5))
print("Q3                 :", kolom.quantile(0.75))
print("Nilai maksimal     :", kolom.max())
print("Kemencengan (skew) :", round(kolom.skew(), 2))

mode = kolom.mode()
print("Nilai modus        :", mode.values[0])
print("Jumlah modus       :", kolom.value_counts()[mode.values[0]])

print("Standar deviasi    :", round(kolom.std(), 2))
print("Variansi           :", round(kolom.var(), 2))

Jumlah data        : 150
Rata-rata          : 3.05
Nilai minimal      : 2.0
Q1                 : 2.8
Q2 (Median)        : 3.0
Q3                 : 3.3
Nilai maksimal     : 4.4
Kemencengan (skew) : 0.33
Nilai modus        : 3.0
Jumlah modus       : 26
Standar deviasi    : 0.43
Variansi           : 0.19